x=0
y=1
z=2
WINGS = "WINGS"
BODY = "BODY"
WINGS_AND_BODY = "WINGS_AND_BODY"


WINGS_AND_BODY_SAME_MODEL = "WINGS_AND_BODY_SAME_MODEL"
ALL_POINTS = "ALL_POINTS"
ALL_POINTS_REPROJECTED_MASKS = "ALL_POINTS_REPROJECTED_MASKS"


CONFIG = "CONFIG"
H5_FILE = "H5_FILE"
